import { Providers } from "@src/lib/providers";
import "../styles/globals.css";
import type { Metadata } from "next";

export const metadata: Metadata = {
  title: "TairuGPT",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en">
      <body>
        <Providers>{children}</Providers>
      </body>
    </html>
  );
}
